name: Deploy Website
# This is a basic workflow to help you get started with Actions

on:
  push:
    branches: [ master ]
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: Making Build folder
      run: yarn build
    - name: Install surge
      run: npm install -g surge
      - name: Run surge
        run: surge ./build furqan-Asign-1.surge.sh --token ${{ secrets.SURGE_TOKEN }}
